[build-system]
requires = ["setuptools>=80.9"]
build-backend = "setuptools.build_meta"

[project]
name = "HydroPatch"
version = "1.5.1"
license = "MIT"
authors = [
  { name = "DaviisDev", email = "bubbalooteam@proton.me" },
]
keywords = ["hydropatch", "hydro_patch"]
description = "This package will add middlewares, routers and fsm for Hydrogram."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "hydrogram @ git+https://github.com/hydrogram/hydrogram@dev",
]

[project.urls]
"Homepage" = "https://github.com/DaviisDev/HydroPatch/"
"Bug Tracker" = "https://github.com/DaviisDev/HydroPatch/issues"
